language: python
python:
- '2.7'
- '3.6'
install:
- pip install -r requirements-dev.txt
- python setup.py install
script:
- nosetests --verbosity=2 tests/
- after_success 
- test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && python3 setup.py sdist && python3 setup.py bdist_wheel --universal && twine -u ${USERNAME} -p ${PASSWORD} -r https://pypi.python.org/pypi register dist/*.whl && twine upload -u ${USERNAME} -p ${PASSWORD} -r https://pypi.python.org/pypi  dist/*.tar.gz
env:
  global:
  - secure: bYBWuv+WDN9EXlIHB7LR8rPbc3NaDRULWpSiuGkUBRE5rTH54xKfVkGQ/za2AQYjN/IFHF3+dLzoz/TDyFdAk4oGdqynIOBnh05nzwQWGX+fHie6x5gWDUg6MGoo1LUelhuld5qTaqtfirMkamwIq3LEXUtMuaxXdN458TPwooCOQ8vtc0iRRLvV/4xgOVb69RaT6i/GQdECj4X35JVt9o6eE70chCnWPYCXw72uvrAeL06GfTBxcIyle+DsgYaCbvCWwl7f3E94kDkAtMSS4ntp66T/yQ6pOQz0Fd39NO+Y/DlYA26yEphgNapfCQV0OhNRJUNLjWvJsy3xMehLUzfM9GxN4Ij6xpRKw3vHCfOxmX8Q4ylma0UghlmvSuo67W1wV5AaMzxAjMpL+nBDPiCVaJWjKCsoQwptq8wtLP5LprhGolTLEFZSPYQxobyxQjj3cQPAY+aA8mxyBBscahe21uGhKE/Aut7+eygar3v5KK09+H1Dsz18iGvzSBEwDrVLqpWQiv9gJD8079BZDSIijQJn0m/xUpiJQcnG5W53Xt4FGMeOzE4CqF2FajxbbXsVRM3DNLeCz583nAr+L8dqu4eCq0WDvGUPifVlpohS7VSrzCdB3acZlxE7jfDZA6JBMTa/km1KjRdUbeW1M6SXlbDAO9NOU7EcC6s2gqs=
  - secure: CMMjBqE3rsmuz1EWP1Dvw5cAgrlZycjT4VTRpGau0GaqWbO0YlYxjOb40uvAfFYFncxuCuoKAj8Xgc4DQ7JLjQRa7BZMxuEghJZn//IcjKnyXRxzji7H3zmZeeYoAhtZYWLlhe8KpKUhAe7+vV4dvO1JEkTUWnIEqtpY39rd5yKeW2i19GqiDy/oe97yoTKQoTk5B+Xj1wmmwMUtVKsMCHu3btMfdRG5gdiqpYjE5Cg3XnMlmD0+zegs/U4lAlETX5tQN9kE27bBjOzIkEA5OgDVGCII4F59jetqSUUDbuqyaGRO5Q/QcQVZmK2rAIJob026cG635A5ymJdVjacnt5zFTDu7L5yzZEMFY27v5V5tcKa6+TTvDGgPOIKHyOCFr2thtySFvq0t31wWKR8rSLQ9qOt/ikJPHFrefv/vUMgF7UXXtcAKAq/+8qPkalDp68EGtgSrPXxNHbn9lXFd2Gl+HN2uWN6blkgctYDZza4N1ICraTcOMUnAEiPQduRkRX/J4JmW/k/ehTVZDdu+0eTpccy5YHm/2sAbblG925/rQOY8eWxhGraZIAPzE65PWeFua7QLl5/eXxLn3rseczTGSLAWt3C1vCID9/yu22A18FXBx/aVA+OjSuPnkjJbaCLs1dRu4LSnsWQHwsQ3s/dy8KYTXfnBPDYQpMsd7GA=
