language: python
python:
- '2.7'
- '3.6'
install:
- pip install urllib3==1.23
- pip install -r requirements-dev.txt
- pip install google-compute-engine
- pip install twine
- python setup.py install
script:
- nosetests --verbosity=2 tests/
after_success:
- test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && python
  setup.py sdist && python setup.py bdist_wheel --universal && twine -u ${USERNAME}
  -p ${PASSWORD} -r https://pypi.python.org/pypi register dist/*.whl && twine upload
  -u ${USERNAME} -p ${PASSWORD} -r https://pypi.python.org/pypi  dist/*.tar.gz
env:
  global:
  - secure: TeTGvEJ56ZjN0f7SXFgH1pkmUShIiVsNNQyEIfKZy4Zk4swgQa++9Nel0YthM8D9whogTMS0Vfg60XXCeXx/p74xMlAmq1B3bNcC0IHYMneZRHu1V8ZGcJqbWBxg8oRuQqx/QgTLy2xQ42Q2LwK4jUg3dVr38uxCj5YI77flK00hTjTw03N9ymhsUP364pELghZzqBNtl8JL1U1xXUnLAUReQJaOQKR5sN5w7TpVKSNzMMKQ2jAW0pK8HrNlpBAk/1sYGLymXQjfyRQh732IDnGAF8kf6wFQ7A1/rmMXu6MQvhijL+y0r6yTscJfYrBoXxlXKI+O1g8m0pE4+UWDh4SDnTw6oFnLOHs7OdosHa7qgneBOa2QI3xZVgTYdUBVgvUCNXOHFgZDqSzvLxxGtZpzvjzvIisHTlONftwuf6o39vrnTfmJMS9Z06BQVYxBF7bow7ldhlEdMg4M8lqZzIvkIUP5fUXHz3Lra1SfoDI3+JcOemsQSs1/DNGE/lPydNLIrow9e9ysdBEVy6FabpmbSwGH5qpWeHo4qCVo8+9B0nt5qRl7SIB5xf2+4p7z3G7vWVb2hmT8YIBla07unc13KhNqbhbQMxgMCshpPptsW7EGN35gfYqptL5ReG0oMPvjxBymjFjVYkYOdSdfLO4pLPLaR0T2sGxKFHpC0yo=
  - secure: lZwArLMIME6XrNMvQXrhVKNn1HyZuEWoovK32lCohNtHp3cjXY1N5iRoz5umfFsa2I8I36Skcw+3BxTFBhs41caS/BcnylY2ON9n6puA9DfOaIq0IANnzgzBB/zSFKYqt0zTbr1t19E+un8lhJFaIY1TfkW0epMWxAig6f7A3/uet7c04Uh0XJrFrOUQ0z+PMIdJnY0WIczP8JmkUjw8sn16kNJSVCT473OyXcLRlcDikQXZboFeSfGC4CQKEcoxMmXEjqt1DOZNiWK5XyDZG5IwNM8EF8RSiPpZ1rzBSPOh7+H9fducZqat8aHQbmTd+IF70oRxtcz1+4xlpHpl96hehJcbDckDwC7/KaVOilb8NV6s1qNa/qguFn2YHEKn7x3noe3rtLXN/PW+dDSCFlVwrSD1ZltUnBdAh50LcNYV2KZMYW9UBHyWjHIn00U2T7n0sUPSUeOTAqpGsyG87WpqUj4Bdacq/bKUPF8iEbvgvgA99/sKObK8OKnpoUr4kdUi2W4egfnBz7PTB6kIdL/C4U284IXsQBORLRrOpWpW2TQ65k6Kdcq5ertHRON27sIu2MQoSM0qoSi7eWz8Qmb5ql9bnOFg+xY6QLE57oeBpzmDQXL3sGhZQwjSQERVpzMiswbI3JSodzYxbizLuiBrU5iDTvmjBeRae+l6nmM=
notifications:
  slack:
    if: branch = master AND (type = push OR type=cron)
    on_success: change
    on_failure: always
    rooms:
      -  secure: lL7sg30YyDduAeBUP3izaQnyjcFqHoVWdy5fn6KkRIX3562m4viqP7IZ8g0pVHOoPi5r+C4Sc6Ybj6yGqM0/RPnQjJ4o68Vv8K7bS77DhKGt+AaVKXG+XrTYyhk2oFybCTV+YTAmMTkoLANdQBtBYCGhIOHWLH7gehWManXgX/KmCJGBi1SBqKpl9NeWHCJzwYS0goJ3kDh1MJa5ZO5K1qKYRWSiAYeUXATkjJphtNZUOXGbmx4RFzRibiTndonQw24riQw6ZTO5IPIObK7YVDZkRh/wFErdQfbkRpUfkP97HsgIdWfONBIB8vUIQ7Ju3oWhtWZ+2WOCoHARCTHZf4kzONJVaCnCfgZSLBDBEr8MVoVHm2tBn/iea/0whD36SaUXU84E9iLF1Sxc53CBdqin29lYlfIhvs/NmVYQ/pGOe0/BFIwegeILOb3pm2Ne+8k4pnYGl+hIJixhiiTDTR5As1IG/Bv0vOlttuoAvDyL+4QxOU6Jzdy+yf1MVqsGcrnfR/HpF7Y3ztqB7et8nlsdYV7GYQ6nI6SuOrXEpwsnlG2Do5iqfz14AuqH8zRkqosy8rURbjvItutqlvkrD7DV/eKRpe+KQDQwhOsdiLvgKltEG241WTOIu/7xTCXgj6+gh5cOAFR7XYmOMVtN39ZoBkLzy+Yzbr3sLmZMXOA=
