language: python
python:
- '2.7'
- '3.6'
install:
- pip install -r requirements-dev.txt
- pip install twine
- python setup.py install
script:
- nosetests --verbosity=2 tests/
- after_success
- test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && python3
  setup.py sdist && python3 setup.py bdist_wheel --universal && twine -u ${USERNAME}
  -p ${PASSWORD} -r https://pypi.python.org/pypi register dist/*.whl && twine upload
  -u ${USERNAME} -p ${PASSWORD} -r https://pypi.python.org/pypi  dist/*.tar.gz
env:
  global:
  - secure: m5I6qo1H7E+CxF98uJuBgje80BuRvG5cX6Q02Ykfu9vGWGYaGQqPplIsq6uLjVa18SExqAm+hUX5xuL/8xIvINZ+0UTtkrNEq4KByCJ1OmuNr/A1Wiv2GlxLGZmenQpomqlnYT5bBw/tnDw/a/F3W5w7cg9TGbK6WUfgWoe4cqiustaL8gniocyS9vmojVEUAdyDKwx/Fd31ttOVl0G8nIOdjyLsr/N85CsDhjaLAJjNiAAAd+K9Y7bNlhAJsxAD1fuNlb2mbbXhjLG832LNXBLv/Mm7PKAf/BMfF8GQdXXjHwfA8iSmS10SHT3TbIHYIGcT4/8OJBb1DcTMB/e3uHusX4Ou0zlxKDXPwKuJjqzdXtlx2i5aG+LLAJGXuP1xoo+Rh7TUl7ml+8wTKkqgFdjwl3DdKx3aHY2beLPPe3B01ypcCFxilRC8uYIdYFNEMTApybWJJGi/RC8XzH4Iu72r5Sr9p1OxPAoaEZv9KDV5RyAGmVrg32O47CYuPARsZarSDwweTuMXY6WegDmculDfsw1kRZ+IqhGtCshJRzT6I04MUN5Xx6kzxaz1Ho9D/ItGTDwNyzLLaE6CcLgZeF06FVgnBaVMv6fEds02b/9qnfG3QYBAf2hwHtdE8C8LhQulTu4wjMMYzSDkM3zSv10L82wkz0L1SsIEsUWJRAY=
  - secure: ToU+lMXvHlJTS2Lx77XanUJgR8lPL+q1OiTFvfTLSv0dmNa9oSPhast0fMoYEyp+AMv3Z2TXWrXWsdUCKvIYddreAUWziUzmWiRdwy4BDvxGN91dPcZijRSNoRuKenJXLpImQZeTPWKQDnXAZ3oQ31l2X2YUB7CjLC3AEooq7LETRAhV7kCJ+cNsuJt93/cWytq/42dMFQkaa3yDvKX6LUsE26MYR+PFnbew1JOwv84sPMHGjhyZUnT+gyVvhL/uCnI9glWvef8xxgOoGpshMkOdXaYPi3nlzCJXoFagNMuYmC7QuVAN+9S2scOlV58BJOKh739xCiNqUtEAhuMgR5d8orzrrQsiv7YQ2UETVquGKy31Uy8nxQR0pkPKvrF7l3HvPoDl8MWG7fTln0dv9Zc5vOY1o89V855pFGd2g+3Jf/x7h7rGszs6cdr0ey+pEo5f+8IiZ5oalqXAOiMlxvkDsrD/OAsLclGB7GKApnAVq07gdG3OPyzEXI99aliXlQ/gnQpaWncgmMz/esoc19hOt23EdV2CVSTjTqTHrYEuHUwXYl2pXsA6zNQd/9xBV5M75BOUEIfq7Ce6BpWIlh97qk+4RxSk1lVM7CzNXW/3jJ3Ki8cQzFfKTDsZQtHUBI6OHnywAmoX/vsbIR3aTxFAVFWleySbirpcyCVvM08=
