language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements-dev.txt
  - python setup.py install
#run tests
script:
  - nosetests --verbosity=2 tests/
