# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ master ]

jobs:
  Build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [2.7, 3.6]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-compute-engine
          pip install twine
          pip install -r requirements-dev.txt
          python setup.py install
      - name: Run Tests
        run: |
          tox
      - name: Upload coverage report to CodeCov
        uses: codecov/codecov-action@v3.1.1
        with:
          files: coverage.xml # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true
      - name: Slack notification when master build fails
        if: ${{ failure() && github.ref == 'refs/heads/master'}}
        uses: rtCamp/action-slack-notify@v2.2.0

        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: cerberus-alerts
          SLACK_MESSAGE: 'Cerberus main build has failed :build-failed:'
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          SLACK_TITLE: Cerberus Build Failure Notification
          SLACK_USERNAME: GitHub Actions
